// These enums were previously generated by Prisma for PostgreSQL.
// SQLite does not support native enums, so they are defined here as TypeScript enums.
// Values are stored as strings in the database.

export enum StatusEnum {
  pending = 'pending',
  preparing = 'preparing',
  ready = 'ready',
  done = 'done',
}

export enum TableStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  RESERVED = 'RESERVED',
}

export enum UnitOfMeasurement {
  kg = 'kg',
  g = 'g',
  liter = 'liter',
  ml = 'ml',
  piece = 'piece',
  pack = 'pack',
  box = 'box',
}

export enum UsageReason {
  production = 'production',
  waste = 'waste',
  adjustment = 'adjustment',
  expired = 'expired',
}
